---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "Model Results Leaflet Map"
subtitle: ""
summary: ""
authors: []
tags: []
categories: []
date: 2020-08-23T13:50:21-04:00
lastmod: 2020-08-23T13:50:21-04:00
featured: false
draft: true

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
library(tidyverse)
library(tidycensus)
library(sf)
library(leaflet)
library(leaflet.extras)
library(widgetframe)

options(scipen = 999, digits = 4, tigris_use_cache = TRUE)

full_predictions <- read_csv("data/full_prediction_percent.csv", 
                             col_types = cols(.default = "c")) 

tract_info <- read_csv("data/combined_census_data_tract.csv", 
                       col_types = cols(.default = "c")) %>% 
  mutate(across(total_population_housed:housed_population_density_pop_per_square_km, as.numeric)) %>% 
  mutate(across(where(is.numeric), round, digits = 2))

full_predictions_small <- full_predictions %>% 
  select(GEOID, mean_city, pct_correct) %>% 
  mutate(GEOID = as.character(GEOID),
         across(c(mean_city, pct_correct), as.numeric),
         across(c(mean_city, pct_correct), round, digits = 2)) %>% 
  left_join(tract_info) %>% 
  mutate(across(c(mean_city, matches("pct")), ~. * 100))

glimpse(full_predictions_small)

tracts <- get_decennial(year = 2010, state = "PA", county = "Allegheny County", 
                        variables = "P001001",
                        geography = "tract", geometry = TRUE) %>% 
  st_transform(crs = "WGS84")

pgh_official_boundary <- st_read("data/Pittsburgh_City_Boundary-shp") %>% 
  mutate(geography = "City boundary") %>% 
  st_transform(crs = "WGS84") %>% 
  st_cast("POLYGON") %>% 
  filter(FID != 7)

tract_pred <- tracts %>% 
  left_join(full_predictions_small)
```

```{r}
bounds <- tracts %>% st_bbox() %>% unlist()

names(bounds) <- NULL

prediction_palette <- colorNumeric(palette = "viridis", domain = tract_pred$mean_city)

labels <- sprintf(
  "Census tract ID: %s
  <br/>Average city classification: %g%%
  <br/>Model correct: %g%%
  <br/>Percent white: %g%%
  <br/>Percent of housing units owned with a loan: %g%%
  <br/>Workers: %g
  <br/>Housed population density per sq km: %g
  <br/>Percent of housing units rented: %g%%
  <br/>Jobs: %g
  <br/>Percent black: %g%%",
  tract_pred$GEOID, 
  tract_pred$mean_city, 
  tract_pred$pct_correct,
  tract_pred$pct_white,
  tract_pred$pct_units_owned_loan,
  tract_pred$workers,
  tract_pred$housed_population_density_pop_per_square_km, 
  tract_pred$pct_units_rented,
  tract_pred$jobs,
  tract_pred$pct_black,
  tract_pred$pct_units_owned_entire) %>%
  lapply(htmltools::HTML)

map <- leaflet(tract_pred) %>% 
  setView(lat = 40.441606, lng = -80.010957, zoom = 10) %>% 
  addProviderTiles(providers$Stamen.Toner, 
                   group = "Toner (default)",
                   options = providerTileOptions(minZoom = 10)) %>%
  addTiles(group = "OSM") %>%
  addMapPane("Census tracts", zIndex = 400) %>% # shown below ames_circles               
  addMapPane("City boundary", zIndex = 490) %>% # shown above ames_lines 
  addPolygons(#data = tract_pred,
              weight = .5,
              color = "black",
              fillColor = ~prediction_palette(mean_city),
              fillOpacity = .8,
              #
              group = "Census tracts",
              #
              highlightOptions = highlightOptions(weight = 5,
                                                  bringToFront = TRUE),
              #
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto"),
              
              #
              options = pathOptions(pane = "Census tracts")
              ) %>% 
  addLegend(pal = prediction_palette, 
            values = ~mean_city, 
            opacity = 0.7, 
            labFormat = labelFormat(suffix = "%"),
            title = "City classification %",
            position = "bottomright",
            
            group = "Legend") %>% 
  addPolylines(data = pgh_official_boundary,
               weight = 10,
               stroke = TRUE,
               color = "black",
               
               #
               
               group = "City boundary",
               options = pathOptions(pane = "City boundary")
               ) %>% 
  addPolylines(data = pgh_official_boundary,
               weight = 2,
               stroke = TRUE,
               color = "yellow",
               
               #
               
               group = "City boundary",
               options = pathOptions(pane = "City boundary")
               ) %>% 
  addLayersControl(
    baseGroups = c("Toner (default)", "OSM"),
    overlayGroups = c("Census tracts", "City boundary", "Legend"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>% 
  addFullscreenControl()

map
#frameWidget(map)
```
